declare module 'react'
declare module 'gatsby'
declare module '@emotion/core'
declare module '@emotion/styled'
declare module 'tailwind.macro'
declare module 'react-use'
declare module 'react-intersection-observer'
